"""'Init'

Revision ID: d5da323ca536
Revises: 
Create Date: 2023-11-06 00:56:17.779695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5da323ca536'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cats', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('cats', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('owners', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('owners', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('owners', 'updated_at')
    op.drop_column('owners', 'created_at')
    op.drop_column('cats', 'updated_at')
    op.drop_column('cats', 'created_at')
    # ### end Alembic commands ###
